### ISSUE TITLE
Verbatim string literal to handle multiline SOQL

### ISSUE THREAD

**Issue by TheMadPope** [apexsharp/apexparser#1]
Error on transpile with something like:
```
mapProg = new map<id, Program_COM__c>(
                [select Id, Name
                 from Program_COM__c 
                 where Id in :setPId]);
```

Transpiles with a simple double quote instead of a @ to make a verbatim string literal. Transpiles to:

```
 mapProg = new Map<ID, Program_COM__c>(Soql.query<Program_COM__c>("select Id, Name
                 from Program_COM__c 
                 where Id in :setPId", setPId));
```

Should be:
```
 mapProg = new Map<ID, Program_COM__c>(Soql.query<Program_COM__c>(@"select Id, Name
                 from Program_COM__c 
                 where Id in :setPId", setPId));
```

**Comment by jayonsoftware** [comment]
`Map<ID, Program_COM__c mapProg = Soql.query<Map<ID, Program_COM__c>("select Id, Name  from Program_COM__c where Id in :setPId", setPId));`

I thought we need some thing like above

**Comment by yallie** [comment]
Good catch, thanks!

**Comment by yallie** [comment]
Updated the Nuget package: [v0.6.6](https://www.nuget.org/packages/ApexParser/0.6.6).
